name: Android build Debug Apk
on:
  workflow_call:
jobs:
  debug-apk:
    name: Generate Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'zulu' # See 'Supported distributions' for available options
          cache: 'gradle'

      - name: Build debug APK
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: kotlinBestPracticeApp.apk
          path: app/build/outputs/apk/debug/app-debug.apk